### ISSUE TITLE
Can mpi4py support running processes across different nodes within a cluster?

### ISSUE THREAD

**Issue by Zarca** [mpi4py/mpi4py#16]
Hi,
As the title said, dose the mpi4py support running multi processes on different nodes(a cluster )
and do mpi operaions between them?

**Comment by Zarca** [comment]
Forget it, i have found that it support :)

**Comment by AymenFJA** [comment]
@Zarca  Can you show us how? I could not find any documentation. Any help Is appreciated.

**Comment by dalcinl** [comment]
mpi4py is not the right place for such a documentation, although [we cover the basics](https://mpi4py.readthedocs.io/en/stable/tutorial.html?highlight=mpiexec#running-python-scripts-with-mpi). 

Look for your MPI documentation, or perhaps the batch system installed in your cluster/supercomputer.
You just need to execute `python script.py args ...`. Sometimes you have to use `mpiexec python script.py ...`, or `srun python script.py ...`. But it all depends on the system, and mpi4py has no control over it.

**Comment by AymenFJA** [comment]
Hey @dalcinl, thanks for the fast response.
To be more specific: 
I am trying to deploy `MPIPoolExecutor` to run on more than one compute node. I do understand that to run MPI executable you need to do `mpirun or mpiexe etc. followed by the number of processes `. 

My question is does the `MPIPoolExecutor`  scale beyond one compute node, or it is bounded within one node. If so, is there any documentation regarding that, or it is a natural behavior that once you start the `executor` it will execute on `multi-node` (assuming I provide a sufficient number of processes)? 

Thank you in advance.

**Comment by dalcinl** [comment]
Look again at the title of this issue, I understand it was a rather general question, so I assumed you did not know about `mpiexec` and friends. Your question is actually quite more specific it is about  `mpi4py.futures`. 

Of course it supports multiple nodes! That's the whole point of implementing the thing with MPI rather than using the plan `concurrent.futures` package. `mpi4py.futures`, being fully implemented with MPI, does not care where the MPI processes run.

Please read [this docs](https://mpi4py.readthedocs.io/en/stable/mpi4py.futures.html#command-line), you may need to use the `python -m mpi4py.futures script.py` hack to get things working in a cluster in case MPI spawn does not work.

**Comment by AymenFJA** [comment]
Thanks for clarifying that.
