### ISSUE TITLE
Rename/add synonyms for __cuda_array_interface__

### ISSUE THREAD

**Issue by FreddieWitherden** [mpi4py/mpi4py#163]
Recent versions of AMD's HIP when paired with UCX-enabled MPI libraries are functionally equivalent to CUDA-aware MPI libraries.  (That is to say one can pass pointers to GPU buffers to MPI routines.)  It might therefore be worth considering using a more generic name for `__cuda_array_interface__` or add synonyms for it (such as `__hip_array_interface__`).

**Comment by dalcinl** [comment]
What's in a name? I believe CuPy will export `__cuda_array_interface__ ` even if using AMD's HIP. I'm not sure if Numba supports HIP. Also note that at this point `__cuda_array_interface__` is legacy stuff, and the future is DLPack (which mpi4py already supports).

@leofang Am I missing something?

**Comment by leofang** [comment]
Sorry for late reply, slowing catching up things after returning from a break.

@FreddieWitherden It may seem obvious to pick a more accommodating name, but there are actually several issues to be understood. I can assure you that we (at least I) have given plenty of thoughts and efforts to cover accelerator-aware MPIs' needs, including this and the other issue you raised. The takeaway here is 1. renaming the interface is not our call, 2. we already support HIP via DLPack. 

First, we started by following the community decision (initiated by Numba folks, see [here](https://numba.readthedocs.io/en/stable/cuda/cuda_array_interface.html)) to support interoperability **across libraries** via CAI (note the emphasis). In other words, if other libraries are not on broad with any proposed change of the protocol, including the name, it is meaningless to do so. And it is actually *very hard* to get interested parties on board.

Second, this very idea was actually proposed by me long ago, discussed and eventually dropped, see https://github.com/numba/numba/issues/4566. One reason is, as @dalcinl mentioned, Numba no longer supports ROCm/HIP, but more importantly the stream semantics, which is taken care of in v3 of the CAI protocol, is different on HIP, see my comment [here](https://github.com/numba/numba/issues/4566#issuecomment-756577522). While this can be worked around easily by branching out on HIP, it makes little sense to attach the same support under the CAI name, so
> I believe CuPy will export `__cuda_array_interface__ ` even if using AMD's HIP.

is incorrect. CuPy disables CAI on HIP.

Finally, in a more recent effort (Python Array API standard) we (the [stakeholders](https://data-apis.org/array-api/latest/purpose_and_scope.html#stakeholders), not us on mpi4py, though I'm also involved), decided to go with DLPack to try and cover the existing hardware spectrum, see the resulting `__dlpack__` protocol [here](https://data-apis.org/array-api/latest/design_topics/data_interchange.html#dlpack-support). This support has been made available in mp4ipy (since v3.1.0), CuPy, NumPy, PyTorch, etc, so things should just work if you're using any of these projects together with mpi4py.

(Note that this protocol is independent of the Array API standard and we'll eventually host the content elsewhere; we need it here only for completeness before a separate DLPack webpage is set up.)

So, I am closing this issue as it's a "won't fix", but please do feel free to raise any questions you might have.
