### ISSUE TITLE
Unable to make mpi4py RMA work

### ISSUE THREAD

**Issue by rdruilhe** [mpi4py/mpi4py#166]
Hello,

I am trying to run the RMA example found [here](https://github.com/mpi4py/mpi4py/blob/master/demo/compute-pi/cpi-rma.py) in the repository of mpi4py. The script is working on a single node with 2 processes but not in a distributed way, i.e., 1 process on 2 nodes. I got the following error:

``` 
Traceback (most recent call last):
  File "/python/cpi-rma.py", line 39, in <module>
    win_n  = MPI.Win.Create(None, comm=MPI.COMM_WORLD)
  File "mpi4py/MPI/Win.pyx", line 77, in mpi4py.MPI.Win.Create
mpi4py.MPI.Exception: MPI_ERR_WIN: invalid window
Traceback (most recent call last):
  File "/python/cpi-rma.py", line 36, in <module>
    win_n  = MPI.Win.Create(n,  comm=MPI.COMM_WORLD)
  File "mpi4py/MPI/Win.pyx", line 77, in mpi4py.MPI.Win.Create
mpi4py.MPI.Exception: MPI_ERR_WIN: invalid window
```

I tested it on 2 different clusters and with mpirun or slurm, always the same result. I also tried to add the solution described in the issue #34 but the issue remains.

Note that I ran another RMA [example](https://rookiehpc.com/mpi/docs/mpi_win_create.php) written in F90 and it is working fine in a distributed mode.

Is there some required dependencies that need to be installed on the clusters for the RMA to make it run with mpi4py, something I am missing? Or is just RMA not available in distributed mode for mpi4py? I am using the latest version of mpi4py and Open MPI 4.1.x

Thanks for the help,

Best regards.

**Comment by dalcinl** [comment]
There is nothing mpi4py is doing to prevent your code from running in distributed mode. mpi4py requires absolutely nothing extra beyond Python and an MPI implementation.

This is most likely an Open MPI issue or something else in your system. Many times the issue is related to MPI thread support. But you said you tried that path, and it did not work. A last trick you may try is to set the environment variable `LD_PRELOAD` to `/path/to/openmpi/lib/libmpi.so`, but that shouldn't really make a difference with a recent Open MPI.

You should ask Open MPI folks about how to debug this issue. There should be verbose options that could tell you if any of the Open MPI components are failing to load. Or they may tell you about how to force the use of a specific RMA component that is guaranteed to work.

**Comment by rdruilhe** [comment]
Ok, thanks for the answer ! 

I will discuss with Open MPI guys then.
