### ISSUE TITLE
mpi4py.futures.MPIPoolExecutor hangs on more than one node and uses only processes on the first node.

### ISSUE THREAD

**Issue by etijskens** [mpi4py/mpi4py#172]
Hi,
I tried to run the [example from the documentation](https://mpi4py.readthedocs.io/en/stable/mpi4py.futures.html#examples) on a cluster. I adapted the code a bit to print the rank/size/processor name inside every call to `julia_line`. When using all cores from a single node it works fine.  However, when using two nodes, the output shows that it only uses the cores on the first node, and hangs in the end, eventually yielding `wall_time exhausted error`. 

If anybody successfully used mpi4py.futures.MPIPoolExecutor on more than one node, I would be very happy to get some info on the used job script (btw our systems use PBS/Torque but slurm examples are Wellcome too) 

Any suggestions to extract more info from the run or to  possible causes of this behaviour are welcome.

Many thanks in advance 
Bert - HPC consultant Flemish Supercomputer Center

**Comment by dalcinl** [comment]
That sounds like an issue with the backend MPI implementation.

Try to run the equivalent to the following command, using `$NP` large enough to spawn multiple nodes. Does it work?

```
 mpiexec -n $NP python -m mpi4py.bench helloworld
```

**Comment by etijskens** [comment]
Kindest regards,

Dr [Engel]bert Tijskens - HPC Analyst/Consultant
Flemish Supercomputer Center
University of Antwerp / Computational mathematics
++32 3 265 3879, ++32 494 664408

On 27 Jan 2022, at 15:02, Lisandro Dalcin ***@***.******@***.***>> wrote:


CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.




That sounds like an issue with the backend MPI implementation.

Try to run the equivalent to the following command, using $NP large enough to spawn multiple nodes. Does it work?

 mpiexec -n $NP python -m mpi4py.bench helloworld


Not

mpiexec -n $NP python -m mpi4py.futures helloworld

?


—
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmpi4py%2Fmpi4py%2Fissues%2F172%23issuecomment-1023241440&data=04%7C01%7Cengelbert.tijskens%40uantwerpen.be%7C0f31670cc96f42feeb6a08d9e19d9ae6%7C792e08fb2d544a8eaf72202548136ef6%7C0%7C0%7C637788889288634032%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2Zlpo86N2u%2FYPj7BvNJ6REWDpOEonjmzH1JmooVS0ps%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACRDDFQKDQUA5CLUHA3LJNLUYFF53ANCNFSM5M5TY74Q&data=04%7C01%7Cengelbert.tijskens%40uantwerpen.be%7C0f31670cc96f42feeb6a08d9e19d9ae6%7C792e08fb2d544a8eaf72202548136ef6%7C0%7C0%7C637788889288634032%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Fu%2FA%2BCkTir9qJrcEMFeUUyqPDuVziLl5kNJPZDUl64s%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cengelbert.tijskens%40uantwerpen.be%7C0f31670cc96f42feeb6a08d9e19d9ae6%7C792e08fb2d544a8eaf72202548136ef6%7C0%7C0%7C637788889288634032%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=W0J5nHlPkr4Gc1GwNaLf0dOlHmKAkmcz2KOnFllmPF0%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cengelbert.tijskens%40uantwerpen.be%7C0f31670cc96f42feeb6a08d9e19d9ae6%7C792e08fb2d544a8eaf72202548136ef6%7C0%7C0%7C637788889288634032%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=H7R7%2FA9byBPHLeh8NRXK1oe69LrfFrWqYrxofNx85OM%3D&reserved=0>.

**Comment by etijskens** [comment]
Is there a way to get info on what is going wrong? There is no info in stdout nor stderr
Kindest regards,

Dr [Engel]bert Tijskens - HPC Analyst/Consultant
Flemish Supercomputer Center
University of Antwerp / Computational mathematics
++32 3 265 3879, ++32 494 664408

On 27 Jan 2022, at 15:02, Lisandro Dalcin ***@***.******@***.***>> wrote:


CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.




That sounds like an issue with the backend MPI implementation.

Try to run the equivalent to the following command, using $NP large enough to spawn multiple nodes. Does it work?

 mpiexec -n $NP python -m mpi4py.bench helloworld


—
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmpi4py%2Fmpi4py%2Fissues%2F172%23issuecomment-1023241440&data=04%7C01%7Cengelbert.tijskens%40uantwerpen.be%7C0f31670cc96f42feeb6a08d9e19d9ae6%7C792e08fb2d544a8eaf72202548136ef6%7C0%7C0%7C637788889288634032%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2Zlpo86N2u%2FYPj7BvNJ6REWDpOEonjmzH1JmooVS0ps%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACRDDFQKDQUA5CLUHA3LJNLUYFF53ANCNFSM5M5TY74Q&data=04%7C01%7Cengelbert.tijskens%40uantwerpen.be%7C0f31670cc96f42feeb6a08d9e19d9ae6%7C792e08fb2d544a8eaf72202548136ef6%7C0%7C0%7C637788889288634032%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Fu%2FA%2BCkTir9qJrcEMFeUUyqPDuVziLl5kNJPZDUl64s%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cengelbert.tijskens%40uantwerpen.be%7C0f31670cc96f42feeb6a08d9e19d9ae6%7C792e08fb2d544a8eaf72202548136ef6%7C0%7C0%7C637788889288634032%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=W0J5nHlPkr4Gc1GwNaLf0dOlHmKAkmcz2KOnFllmPF0%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cengelbert.tijskens%40uantwerpen.be%7C0f31670cc96f42feeb6a08d9e19d9ae6%7C792e08fb2d544a8eaf72202548136ef6%7C0%7C0%7C637788889288634032%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=H7R7%2FA9byBPHLeh8NRXK1oe69LrfFrWqYrxofNx85OM%3D&reserved=0>.

**Comment by EricPgh** [comment]
Lisander, 
I don't know exactly what etijskens is seeing, but it sounds similar to what I was seeing today.  I believe you are correct that it is the MPI backend.  Running the helloworld benchmark on a 4*32 interactive session, I finally found that my MPI dependencies were bad.  At first (on two cpus across two nodes) helloworld gave me 0 of 1 and 0 of 1 outputs.  It was because intel MPI was being called from the conda environment.  Doing a module unload of impi forced the runtime through the conda mpirun executable.  This gave me correct behavior of helloworld, like what you are showing above.  Attempting this with the 4*32 interactive session, I also get correct output of helloworld, and correct output of my own starmap call.  However when I submit a larger request that isn't interactive (through LSF), I get hangs from the mpi backend.  They look like this:

btl_tcp.c:566:mca_btl_tcp_recv_blocking] recv(13) failed: Connection reset by peer (104)

The problem doesn't error and exit though, it seems to hang for as long as the cpu limit permits.  This message will get repeated multiple times (and likely consuming a lot of cputime for each one).  Notably, the error above doesn't even occur during the starmap call.  It occurs just whenever.  (I invoke with mpirun -np $NP -host $HPC_HOSTFILE python -m mpi4py script.py).  Prior to the blocking error, I get this message:

`WARNING: Open MPI will create a shared memory backing file in a
directory that appears to be mounted on a network filesystem.
Creating the shared memory backup file on a network file system, such
as NFS or Lustre is not recommended -- it may cause excessive network
traffic to your file servers and/or cause shared memory traffic in
Open MPI to be much slower than expected.

You may want to check what the typical temporary directory is on your
node.  Possible sources of the location of this temporary directory
include the $TEMPDIR, $TEMP, and $TMP environment variables.

Note, too, that system administrators can set a list of filesystems
where Open MPI is disallowed from creating temporary files by setting
the MCA parameter "orte_no_session_dir".`

The system is a newer HPC, with EPYC and infiniband connections.  I suspect it has to do with the MPI backend since the mpi4py message passing seems to work on that interactive session.  And it may be that the shared memory file is getting removed by the system.  I'm currently chasing this down more, but I thought since I'm using mpi4py and getting hangs while spanning multiple nodes that this might be in the same boat as the OP.

Eric

**Comment by dalcinl** [comment]
@EricPgh IMHO, this just looks like a misconfiguration or a broken MPI installation. Your Intel MPI module is most likely properly configured to run in your cluster. But if you use MPI from conda-forge, you may need special runtime configuration you are not aware of.

One obvious way to fix this issue would be to install mpi4py from sources (using `pip install mpi4py`), such that mpi4py gets built with the Intel MPI installation available via your environment module. However, if you have other MPI-based dependencies, you will have to do the same, things could go wrong eventually, and you will waste a lot of time.

If you are using conda environment and the conda-forge builds, I recommend you read [this documentation](https://conda-forge.org/docs/user/tipsandtricks.html#using-external-message-passing-interface-mpi-libraries) about MPICH'a ABI compatibility (Intel MPI is an MPICH derivative, so you should be able to use it the way these docs explain).

**Comment by dalcinl** [comment]
@EricPgh Any update? Could your figure out what was going on?

**Comment by etijskens** [comment]
unfortunately not. We have been using mpi4py quite a lot on our cluster. It is only mpi4py.futures causing problems.

________________________________

**Comment by EricPgh** [comment]
So as I mentioned the previous build that I was using was the Anaconda version. It was using the openmpi libraries. What I started using with the help of some of our people was a spack build with the mpich Library. The Intel MPI gave me Hydra errors. However even still this wasn't perfect. It would work on interactive sessions but give me 20% intermittent failures on batch sessions. A change in the bootstrap launcher to SSH remove that intermittent failure. However it does seem to affect the fabric and the efficiency of the MPI job. I'm still trying to diagnose that and find the right fabric settings. For me the most efficient has been using the spack libraries with mpich on an interactive session with the lsf launcher.
