### ISSUE TITLE
mpi4py wheels

### ISSUE THREAD

**Issue by Helveg** [mpi4py/mpi4py#28]
A full wheelhouse with something like [cibuildwheel](https://github.com/joerick/cibuildwheel) could help reduce installation issues for standard users. People who need to build against specific MPI libraries can still get the source dists with the `--no-binary` flag. It would also help during doc (#26) and other CI pipelines.

**Comment by dalcinl** [comment]
- On Linux and macOS... How would you solve the MPICH vs Open MPI issue? I don't know what would be the proper way to encode/expose the specific backend MPI dependency on the wheel filename. mpi4py is quite special, it depends on a library that may be provided by two different and unrelated implementations that are ABI-compatible. If you have any ideas about how to properly address this issue, then I'm totally open to it.
- Windows is the platform where things are most painful, and wheels are already available on  PyPI, and using Microsoft MPI.
- Just FYI, for things that do not require an actual MPI like docs, perhaps we can use things like `python setup.py build --mpi=nompi`. Right now it is a bit slow , it runs configure tests for every symbol in `mpi.h`, but this could be hacked around to skip these configure tests.

**Comment by Helveg** [comment]
* Wouldn't we bundle our own MPI libraries into the wheel? Or would they not function with the other MPI programs compiled on the machine?
* I think Microsoft MPI would be the best bet there. Where do these wheels come from?

**Comment by leofang** [comment]
If the wheel is going to bundle a particular MPI implementation, it must be under a different name, say `mpi4py-openmpi` etc. The reason is HPC people almost always use MPI libraries tailored-built wrt their cluster env. These build-time flags vary a lot, and there is no one-size-fit-all solution using wheels. If `pip install mpi4py` brings down a wheel instead of compiling from source (which is the status quo), those people will be very mad at us. Too much surprises.

For "standard" users, I would suggest installing mpi4py from Conda-Forge, which is released as pre-built binaries. We maintain the packages there, with lowest amount of build-time flags set in each MPI libraries. On Linux:
```
conda install -c conda-forge mpi4py openmpi  # mpi4py is built against openmpi
```
or
```
conda install -c conda-forge mpi4py mpich  # mpi4py is built against mpich
```
On Windows:
```
conda install -c conda-forge mpi4py msmpi  # mpi4py is built against MS-MPI 10
```

**Comment by leofang** [comment]
Another issue with MPI built in wheels is interoperability. Not all Python MPI programs perform MPI operations only on top of mpi4py. There could be some components of the program accessing MPI APIs directly at C/C++ level. In order for all these components to correctly use the same MPI library, they must be built against the same MPI at build time, and get the linking right at runtime. I don't think wheels can meet this requirement. Ofc users of such programs can always build from source, but it means the efforts we invest would be wasted. Just my two cents.

**Comment by Helveg** [comment]
Yea that makes a lot of sense. Releasing wheels under seperate names for the libraries would be a good solution for people who want to explicitly choose their flavor of mpi4py without disrupting `pip install mpi4py`.

**Comment by dalcinl** [comment]
It is not just about the MPI library. Actually running MPI applications usually require some additional MPI runtime (e.g. `mpiexec` command). Bundling the MPI libraries on mpi4py wheels is IMHO a bad idea.

**Comment by Helveg** [comment]
Alternative approach. We can release a set Python packages like `mpi4py-openmpi` that bundles the OpenMPI libraries and runtime binaries, or `mpi4py-mpich`, and then we add `extras_require` sets to you do: `pip install mpi4py` to do the regular source installation, or `pip install mpi4py[openmpi]` that first installs a package with the libraries and binaries, then when `mpi4py` is installed it can detect that sub package's libraries and use that to build?

My objectives here being:
* [x] A guaranteed to work default install with `pip install mpi4py[openmpi]` by having the OpenMPI libraries & binaries in the subwheels
* [x] The same install behavior for `pip install mpi4py` unless any of the subpackages have already been installed

I'm making a framework that uses mpi4py for really novice Python users and it's always mpi4py that gives problems as a dependency and I understand why this is, giving its complexity on HPC systems, but I'd like to find a way for it to become a noob friendly pip installable dependency as well.

**Comment by dalcinl** [comment]
@Helveg If you are targeting novices, would't it make sense to teach them to start with the [Miniforge](https://github.com/conda-forge/miniforge/#miniforge) installer and get everything from `conda-forge`?

If mpi4py gives grief to novice users, it is most likely because novice users typically make a total mess of their development environments. Look at mpi4py's CI infrastructure covering mainstream Linux/macOS/Windows, you usually execute a one-liner to install the system MPI, and `pip install mpi4py` works out of the box.

Anyway, I'm not opposed at all to your suggestion, provided it is implemented the right way. Your `mpi4py-mpich` and `mpi4py-openmpi` packages would need to be just a wheel handling the binary installation of the respective full MPI implementation. Most likely, you will have to make these packages relocatable, such that users can install them in any site-packages directory (at least the user one in `~/.local`). Handling binary relocation yourself requires a lot of nasty and platform-dependent stuff, ask  `conda` folks . And then you will the cruel reality: wheels do not have any sort of support for post-install script, so forget about using binary editing tools like `chrpath` on Linux or `install_name_tool` on macOS. I anticipate that you will fail and waste your time. Although you will learn a lot in the proceses. Of course, I could be wrong. But remember this ain't my first rodeo.

**Comment by Helveg** [comment]
@dalcinl https://gist.github.com/Helveg/d7cfc16e80e9e6457a70bc1ceec3b18e

What about a sane subset of install options that provide the binary compatibility we require here?
