### ISSUE TITLE
Script in mpi4py not executing correctly

### ISSUE THREAD

**Issue by matheuswr89** [mpi4py/mpi4py#280]
I'm developing a cluster using mpi4py and when i run a basic script to test the cluster the result is weird:
![image](https://user-images.githubusercontent.com/44068234/201494901-1dabd9f6-6728-426a-9138-a15b55740992.png)
the result should be this (script executed in c):
![image](https://user-images.githubusercontent.com/44068234/201494909-d8f91479-615e-4d81-879a-ebffecbda80f.png)

My code:
```
from mpi4py import MPI

world_comm = MPI.COMM_WORLD
world_size = world_comm.Get_size()
name = MPI.Get_processor_name()
my_rank = world_comm.Get_rank()

print('World Size: {0} | Name: {1} | Rank: {2}'.format(world_size,name,my_rank))
```

And the hostfile:
```
no02   slots=3 
no01   slots=5
```

How could I get around this problem?

**Comment by dalcinl** [comment]
This probably means that your `mpiexec` command is from a different MPI implementation of the one used to build mpi4py. This usually happen on Ubuntu systems, because the have a bit of mess in the way they manage the MPICH and Open MPI packages with the alternatives system. 

My recommendation is to uninstall and reinstall mpi4py, making sure that the `mpiexec` command and the `mpicc` command (MPI C compiler wrapper) belong to the same MPI implementation.  Run `mpiexec --help` and `mpicc -show` to figure out.
