### ISSUE TITLE
ifdown the master node ，the slave is huang forever

### ISSUE THREAD

**Issue by watchpoints** [mpi4py/mpi4py#288]
rank = MPI.COMM_WORLD.Get_rank()
    name = MPI.Get_processor_name()
    size = MPI.COMM_WORLD.Get_size()
    print(name)
    print(size)

    if rank == 0:
        print("master_to_run")
        master_to_run() //ifdown the network
    else:
        print("slave_to_run " + str(rank))
        slave_to_run()

**Comment by dalcinl** [comment]
This kind of behavior is not mpi4py's fault, but the way your backend MPI implementation works.

One thing you can try is running your code the following way:
```
mpiexec -n {NPROCS} python -m mpi4py your_main_script.py
```
If process zero generates an MPI error because of the `ifdown` (but I'm not sure whether such error will trigger), then MPI should abort all the processes in MPI_COMM_WORLD (assuming your MPI behaves properly).
Look here for further explanation: https://mpi4py.readthedocs.io/en/stable/mpi4py.run.html
