### ISSUE TITLE
Python 3.10 mpi4y install error 

### ISSUE THREAD

**Issue by djaym7** [mpi4py/mpi4py#321]
/opt/conda/compiler_compat/ld: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so: undefined reference to `orte_rml_recv_cb_t_class'
      /opt/conda/compiler_compat/ld: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so: undefined reference to `orte_session_dir_cleanup'
      /opt/conda/compiler_compat/ld: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so: undefined reference to `opal_info_show_opal_version'
      /opt/conda/compiler_compat/ld: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so: undefined reference to `opal_datatype_add'
      /opt/conda/compiler_compat/ld: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so: undefined reference to `mca_base_var_group_get_count'
      /opt/conda/compiler_compat/ld: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so: undefined reference to `opal_datatype_resize'
      /opt/conda/compiler_compat/ld: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so: undefined reference to `opal_hash_table_set_value_uint64'
      /opt/conda/compiler_compat/ld: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so: undefined reference to `opal_list_t_class'
      collect2: error: ld returned 1 exit status
      failure.
      removing: _configtest.c _configtest.o
      error: Cannot link MPI programs. Check your configuration!!!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mpi4py
Failed to build mpi4py
ERROR: Could not build wheels for mpi4py, which is required to install pyproject.toml-based projects

**Comment by dalcinl** [comment]
This typically happens when trying to install  mpi4py with pip inside a conda environment. It's hard to help with such a little information.  You did not even provide the full output or ask pip to produce a full log to submit here. 

If you are using `conda-forge`, then `conda install mpich mpi4py` or `conda install openmpi mpi4py` should be enough, no need to install mpi4py with pip. You may also try `conda install mpich-mpicc` or `conda install openmpi-mpicc`, then you should be able to install mpi4py with pip using the MPICH or Open MPI packages available in conda-forge.

If you are trying to do something more advanced, like building mpi4py from sources or installing mpi4py in a conda-forge environment using an MPI installation outside of that environment (that's my guess from the little output you copied and pasted), then you have to be more explicit, explain yourself, and provide all the steps that would allow us to reproduce the failure,  e.g. what Linux distro and version you are in, how did you create the conda environment, the list of packages in your environment, etc.

**Comment by djaym7** [comment]
I'm not using conda. I'm using nividia's docker container, cuda 11.6 Ubuntu 20.x, installed python 3.10, and libopenmpi-dev. While installing mpi4y it throws this error. My PC is away right now, I'll post the dockerfile once I'm back. This is essentially what's happening in it.

**Comment by djaym7** [comment]
FYI : There are other people who has the same issue, they downgraded to python 3.8 and it worked..

**Comment by djaym7** [comment]
Here's Dockerfile: 

FROM pytorch/pytorch:1.13.1-cuda11.6-cudnn8-devel

COPY ./app /app
WORKDIR /app
RUN apt update
RUN apt install curl -y

#install openmpi 
RUN DEBIAN_FRONTEND=noninteractive apt install libopenmpi-dev -y


RUN pip install pip --upgrade
RUN apt install -y git 
RUN apt install -y screen
RUN pip install -r /app/requirements.txt



VOLUME /app

# ENV FLASK_APP=main.py
# ENV FLASK_DEBUG=1 #set in app.run
EXPOSE 8080
ENTRYPOINT ["python","/app/model/launch.py"]




requirements.txt:
mpi4py

**Comment by dalcinl** [comment]
> I'm not using conda.

Yes, you are. "conda" is mentioned right there in the error message. Your `python` command comes from a Anaconda Python installation from `/opt/conda`. I would advise getting some familiarity with the software stack you are using.

Given that you are using docker, the best fix is to add the following command BEFORE installing stuff with pip:

```dockerfile
RUN rm -f /opt/conda/compiler_compat/ld
```

An alternative fix could be
```dockerfile
RUN conda install -c conda-forge ld_impl_linux-64
```

Thanks to @mrogowski for to figure out the issues and suggesting the fixes.

**Comment by dalcinl** [comment]
@djaym7 Could you make it work with any of the suggested solutions?

**Comment by djaym7** [comment]
I downgraded to 3.8, will check back in future
