### ISSUE TITLE
no mpiexec: mpi4py.MPI.Exception: MPI_ERR_WIN: invalid window

### ISSUE THREAD

**Issue by Helveg** [mpi4py/mpi4py#34]
When you don't use MPI wrappers to execute your script (`mpiexec`, `mpirun`, `srun`, ...) most `mpi4py` features function as if you're on an MPI process with rank 0 in an MPI world of size 1. However, when you use the `MPI.Win.Create(buffer, True, MPI.INFO_NULL, MPI.COMM_WORLD)` it throws the following error:

```
--------------------------------------------------------------------------
The OSC pt2pt component does not support MPI_THREAD_MULTIPLE in this release.
Workarounds are to run on a single node, or to use a system with an RDMA
capable network such as Infiniband.
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/robin/Documents/GIT/mpilock/mpilock/__init__.py", line 12, in sync
    return WindowController(comm, master)
  File "/mnt/c/Users/robin/Documents/GIT/mpilock/mpilock/__init__.py", line 26, in __init__
    self._read_window = self._window(self._read_buffer)
  File "/mnt/c/Users/robin/Documents/GIT/mpilock/mpilock/__init__.py", line 38, in _window
    return MPI.Win.Create(buffer, True, MPI.INFO_NULL, self._comm)
  File "mpi4py/MPI/Win.pyx", line 72, in mpi4py.MPI.Win.Create
mpi4py.MPI.Exception: MPI_ERR_WIN: invalid window
```

I don't see why a Window also can't function in a world with size 1.

**Comment by dalcinl** [comment]
> I don't see why a Window also can't function in a world with size 1.

I don't see it either :smile:. 

This is not mpi4py's fault, but Open MPI's. Look at the error message, looks like they do not support RMA if you initialize MPI with full threading support. mpi4py requests `MPI_THREAD_MULTIPLE`, because, you know, we are in 2021, and the concept of MPI thread safety was introduced more than 20 years ago. Besides, `mpi4py.futures` works bests with full thread support, and as I cannot assume how third-party code will use mpi4py, the safest thing to do is to ask for full threading support.

Try adding the following two lines at the VERY BEGINNING of your entry-point script (before the first `from mpi4py import MPI` ever happens).

```
import mpi4py
mpi4py.rc.thread_level = 'single' # or perhaps 'serialized'
```

If that does not work, then sorry, there is nothing I can do.

**Comment by Helveg** [comment]
That works! Is there a way to poll the maximum supported level in `mpi4py`? 

Why would the threading support of OpenMPI change dissapear when I use `mpiexec -n 2 ...`? Is this an upstream bug?

**Comment by dalcinl** [comment]
> That works! Is there a way to poll the maximum supported level in `mpi4py`?

I'm not sure I understand your question. I think you probably want  `MPI.Query_thread()`, that will return the thread support the backend MPI implementation actually provides.

> Why would the threading support of OpenMPI change when I use `mpiexec -n 2 ...`?

Why you say that the thread support changes with `-n 2` ? Just because your code works in that case? I think that's totally unrelated. Use MPI.Query_thread() to double-check.

> Is this an upstream bug?

Perhaps, I'm not a regular user nor a developer.

PS: I believe Open MPI folks are working on replacing this OSC pt2pt component.

**Comment by Helveg** [comment]
> Why you say that the thread support changes with -n 2 ? Just because your code works in that case? I think that's totally unrelated. Use MPI.Query_thread() to double-check.

Under the assumption that it is not a bug, with `-n 2` the code works, which would mean that the OSC pt2pt either isn't used, or suddenly supports the requested full threading support. It was mostly just a premise to conclude that there must be something wonky going on upstream

> Use MPI.Query_thread() to double-check.

In both the `python ...` and `mpiexec -n 2 python ...` case `MPI.Query_thread()` reports `3`

**Comment by dalcinl** [comment]
> `MPI.Query_thread()` reports `3`

That means `MPI_THREAD_MULTIPLE` in Open MPI (look at `mpi.h` for the enum). Well, then there you have, mpi4py requests `MPI_THREAD_MULTIPLE`, Open MPI seems to happily provide it. 

If you run on a single process, Open MPI seems to pick this OSC pt2pt component that cannot work well with `MPI_THREAD_MULTIPLE`. When you ask for two process, then Open MPI may not be loading that component and uses something different, then everything works. Again, sorry, I'm not the one either responsible for or with the knowledge to explain Open MPI to users. Look in mpi4py's mailing list, I believe this issues has been brought up before. Also double-check Open MPI folks, read the docs, or ask them for clarifications.

PS: after a trivial search: open-mpi/ompi#2614

**Comment by Helveg** [comment]
Ok, thanks for looking into this anyway :)

**Comment by flawb** [comment]
mpi4py.MPI.Exception: Invalid root, error stack:

**Comment by dalcinl** [comment]
@flawb Please submit a proper question/comment. I have no idea what are you trying to ask/report.

**Comment by flawb** [comment]
hello, I want to ask the problems as follows :

how can I deal with it, thanks!




裴宏梅
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mpi4py/mpi4py"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月13日(星期二) 晚上10:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mpi4py/mpi4py] no mpiexec: mpi4py.MPI.Exception: MPI_ERR_WIN: invalid window (#34)





 
@flawb Please submit a proper question/comment. I have no idea what are you trying to ask/report.

**Comment by dalcinl** [comment]
I'm still having a hard time understanding your questions, but I'll guess: looks like you are getting an "Invalid root" exception. This probably means that the `root` argument of some collective call like scatter/gather/reduce has an out-of-range value, `root` values usually are in the range `0 <= root < comm.size`. 

When you report errors, you should show a bit of the code or at least the line triggering the error. Also, it is a good idea to paste the full Python traceback. Without that information, it is quite hard to figure out what is going on.

Next time, please open a new issue. This issue is closed and looks most likely unrelated to your problem.

**Comment by flawb** [comment]
enen,thanks !




裴宏梅
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mpi4py/mpi4py"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月14日(星期三) 晚上8:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mpi4py/mpi4py] no mpiexec: mpi4py.MPI.Exception: MPI_ERR_WIN: invalid window (#34)





 
I'm still having a hard time understanding your questions, but I'll guess: looks like you are getting an "Invalid root" exception. This probably means that the root argument of some collective call like scatter/gather/reduce has an out-of-range value, root values usually are in the range 0 <= root < comm.size.
 
When you report errors, you should show a bit of the code or at least the line triggering the error. Also, it is a good idea to paste the full Python traceback. Without that information, it is quite hard to figure out what is going on.
 
Next time, please open a new issue. This issue is closed and looks most likely unrelated to your problem.
