### ISSUE TITLE
mpi4py Installation failure for openmpi-4.1.4

### ISSUE THREAD

**Issue by Dairhepon** [mpi4py/mpi4py#343]
hello,i want to install mpi4py on ubuntu18.04 python 3.9 openmpi-4.1.4
i installed mpi4py-3.1.4.tar.gz and modified mpi.cfg to set the path of my openmpi,but when i execute the command " `python setup.py build --mpi=openmpi`, i meet failure,error outputs are following:
```
running build
running build_src
running build_py
running build_clib
MPI configuration: [openmpi] from 'mpi.cfg'
MPI C compiler:    /usr/local/openmpi/openmpi-4.1.4/build/bin/mpicc
MPI C++ compiler:  /usr/local/openmpi/openmpi-4.1.4/build/bin/mpicxx
running build_ext
MPI configuration: [openmpi] from 'mpi.cfg'
MPI C compiler:    /usr/local/openmpi/openmpi-4.1.4/build/bin/mpicc
MPI C++ compiler:  /usr/local/openmpi/openmpi-4.1.4/build/bin/mpicxx
checking for MPI compile and link ...
/usr/local/openmpi/openmpi-4.1.4/build/bin/mpicc -pthread -B /root/miniconda3/envs/DL/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /root/miniconda3/envs/DL/include -I/root/miniconda3/envs/DL/include -fPIC -O2 -isystem /root/miniconda3/envs/DL/include -fPIC -I/root/miniconda3/envs/DL/include/python3.9 -I/usr/local/openmpi/openmpi-4.1.4/build/include -c _configtest.c -o _configtest.o
success!
removing: _configtest.c _configtest.o
/usr/local/openmpi/openmpi-4.1.4/build/bin/mpicc -pthread -B /root/miniconda3/envs/DL/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /root/miniconda3/envs/DL/include -I/root/miniconda3/envs/DL/include -fPIC -O2 -isystem /root/miniconda3/envs/DL/include -fPIC -I/root/miniconda3/envs/DL/include/python3.9 -I/usr/local/openmpi/openmpi-4.1.4/build/include -c _configtest.c -o _configtest.o
/usr/local/openmpi/openmpi-4.1.4/build/bin/mpicc -pthread -B /root/miniconda3/envs/DL/compiler_compat _configtest.o -Lbuild/temp.linux-x86_64-cpython-39 -L/usr/local/openmpi/openmpi-4.1.4/build/lib -Wl,--enable-new-dtags,-R/usr/local/openmpi/openmpi-4.1.4/build/lib -lmpi -o _configtest
/root/miniconda3/envs/DL/compiler_compat/ld: warning: libm.so.6, needed by /usr/local/openmpi/openmpi-4.1.4/build/lib/libmpi.so, not found (try using -rpath or -rpath-link)
/root/miniconda3/envs/DL/compiler_compat/ld: warning: libz.so.1, needed by /usr/local/openmpi/openmpi-4.1.4/build/lib/libopen-rte.so.40, not found (try using -rpath or -rpath-link)
/root/miniconda3/envs/DL/compiler_compat/ld: warning: libdl.so.2, needed by /usr/local/openmpi/openmpi-4.1.4/build/lib/libopen-pal.so.40, not found (try using -rpath or -rpath-link)
/root/miniconda3/envs/DL/compiler_compat/ld: warning: libutil.so.1, needed by /usr/local/openmpi/openmpi-4.1.4/build/lib/libopen-pal.so.40, not found (try using -rpath or -rpath-link)
/root/miniconda3/envs/DL/compiler_compat/ld: /usr/local/openmpi/openmpi-4.1.4/build/lib/libopen-rte.so.40: undefined reference to `inflate'
/root/miniconda3/envs/DL/compiler_compat/ld: /usr/local/openmpi/openmpi-4.1.4/build/lib/libmpi.so: undefined reference to `log@GLIBC_2.29'
/root/miniconda3/envs/DL/compiler_compat/ld: /usr/local/openmpi/openmpi-4.1.4/build/lib/libopen-pal.so.40: undefined reference to `dlopen@GLIBC_2.2.5'
/root/miniconda3/envs/DL/compiler_compat/ld: /usr/local/openmpi/openmpi-4.1.4/build/lib/libopen-pal.so.40: undefined reference to `dlerror@GLIBC_2.2.5'
/root/miniconda3/envs/DL/compiler_compat/ld: /usr/local/openmpi/openmpi-4.1.4/build/lib/libmpi.so: undefined reference to `sqrt@GLIBC_2.2.5'
/root/miniconda3/envs/DL/compiler_compat/ld: /usr/local/openmpi/openmpi-4.1.4/build/lib/libopen-rte.so.40: undefined reference to `deflate'
/root/miniconda3/envs/DL/compiler_compat/ld: /usr/local/openmpi/openmpi-4.1.4/build/lib/libopen-pal.so.40: undefined reference to `openpty@GLIBC_2.2.5'
/root/miniconda3/envs/DL/compiler_compat/ld: /usr/local/openmpi/openmpi-4.1.4/build/lib/libopen-rte.so.40: undefined reference to `deflateInit_'
/root/miniconda3/envs/DL/compiler_compat/ld: /usr/local/openmpi/openmpi-4.1.4/build/lib/libopen-rte.so.40: undefined reference to `inflateEnd'
/root/miniconda3/envs/DL/compiler_compat/ld: /usr/local/openmpi/openmpi-4.1.4/build/lib/libopen-pal.so.40: undefined reference to `dlclose@GLIBC_2.2.5'
/root/miniconda3/envs/DL/compiler_compat/ld: /usr/local/openmpi/openmpi-4.1.4/build/lib/libopen-rte.so.40: undefined reference to `deflateEnd'
/root/miniconda3/envs/DL/compiler_compat/ld: /usr/local/openmpi/openmpi-4.1.4/build/lib/libopen-rte.so.40: undefined reference to `deflateBound@ZLIB_1.2.0'
/root/miniconda3/envs/DL/compiler_compat/ld: /usr/local/openmpi/openmpi-4.1.4/build/lib/libopen-rte.so.40: undefined reference to `inflateInit_'
/root/miniconda3/envs/DL/compiler_compat/ld: /usr/local/openmpi/openmpi-4.1.4/build/lib/libopen-pal.so.40: undefined reference to `dlsym@GLIBC_2.2.5'
collect2: error: ld returned 1 exit status
failure.
removing: _configtest.c _configtest.o
error: Cannot link MPI programs. Check your configuration!!!
```
it may shows i dont have libmpi.so，but i have that file in the floder，whats wrong with me， can you help me？

**Comment by dalcinl** [comment]
You are trying to install mpi4py within a miniconda environment that has an outdated linker command. Similar issues have already been reported many times, the latest is #335. As I suggested before, a possible quick workaround would be to just remove the linker:
```
rm /root/miniconda3/envs/DL/compiler_compat/ld
```

However, I have an alternative piece of advice: Do you really need to install Open MPI yourself? Would it work for you to use the openmpi package from conda-forge ([instructions here)](https://mpi4py.readthedocs.io/en/latest/install.html#using-conda)?.

**Comment by Dairhepon** [comment]
thanks,it is a good idea to use the command "conda install -c conda-forge mpi4py openmpi", i try it in a new virtual env，and it automaticly installs openmpi and i installed mpi4py sucessfully,it is so convenient.

**Comment by drmichaeltcvx** [comment]
Hi, Lisandro,

Thanks for your prompt response! Indeed I am getting my python from Anaconda.

mpi4py is but a small part of complex s/w framework (called GEOS) that builds a lot of Python packages that carry out XML file processing and qualification tests via the ATS package. GEOS itself contains logic to use pip from plain Python to build the various needed components and it was not written in an Anaconda environment. The build process has several parts hardwired to generate pip command lines. I can try to use the conda route but I suspect other parts will fail. Actually, I need to use virtual environments to install at a user level different packages and regardless of my efforts to successfully build mpi4py the build system keeps installing packages at ${HOME}/.local/lib thus making building a distribution that others can use off an common location impossible.


Thank you much !

Michael

Michael E. Thomadakis
Chevron Technology Center, Innovation and HPC R&D
HOU150, Location  10186; +1-832-854-3859
***@***.******@***.***>

From: Lisandro Dalcin ***@***.***>
Sent: Friday, May 24, 2024 2:30 PM
To: mpi4py/mpi4py ***@***.***>
Cc: Thomadakis, Michael ***@***.***>; Mention ***@***.***>
Subject: [**EXTERNAL**] Re: [mpi4py/mpi4py] mpi4py Installation failure for openmpi-4.1.4 (Issue #343)

Be aware this external email contains an attachment and/or link.
Ensure the email and contents are expected. If there are concerns, please submit suspicious messages to the Cyber Intelligence Center using the Report Phishing button.


@drmichaeltcvx<https://github.com/drmichaeltcvx> Are you installing within a conda environment? Why aren't you just installing mpi4py with conda using an external openmpi? docs: https://conda-forge.org/docs/user/tipsandtricks/#using-external-message-passing-interface-mpi-libraries

conda install -c conda-forge mpi4py 'openmpi=*=external_*'

There are ways to hack on the linker and the flags, but I forgot the details. In any case, this mess is a recurrent problem when people try to build on conda environment. Unfortunately, everyone comes here asking for answers, but the definitive solution is out of my hands. Over the years, I've been removing most hacks related to compilers and flags, simply because it is impossible to maintain.

Alternatively, you could try to use the binary mpi4py wheels from here: https://anaconda.org/mpi4py/mpi4py, these should work with any external MPI (either MPICH or Open MPI) installation.

-

**Comment by dalcinl** [comment]
@drmichaeltcvx Maybe you should contact me to my private email next week to speedup the exchange... 

If I understand correctly, you are using Python from an Anaconda installation (is it the full Anaconda, or the small Miniconda distribution from conda-forge?), but then you have to install everything on a pip-managed virtual environment (not a conda-managed environment)? 

Wild idea: What if you do `export OMPI_CC=cc OMPI_CXX=c++` such that the `mpicc` compiler wrapper would use the system C/C++ compilers?
