### ISSUE TITLE
Xterm hangs on linux when importing mpi4py

### ISSUE THREAD

**Issue by arunjose696** [mpi4py/mpi4py#373]
The xterm terminals launched with below command hangs 

`mpiexec -n 4 xterm -e "python -m pdb my_program.py"`

 my_program.py
```
breakpoint()
from mpi4py import MPI 
print("hello")
```

The same command works fine for other python code,  only fails when a call to mpi.init() is involved.

**Comment by dalcinl** [comment]
What happens if you try:
```
mpiexec -n 4 xterm -e "python my_program.py"
```
As you are calling `breakpoint()` that should be enough to drop you in `pdb`.

Where does the hand occurs? If you provide input in one terminal, you may have to provide it in the other term windows as well, stdin streams should be individual to each window for things to work.

Your example is working just fine on my Fedora 38 box with system MPICH 4.03. 
What MPI implementation are you using?

Ultimately, this issue is most likely unrelated to mpi4py but related to issues with your MPI implementation.

**Comment by arunjose696** [comment]
Thanks for the response
It works fine now, the issue was due to not having all the xterms not executing init() together. I continued after breakpoint only in one window and not in other window.
