### ISSUE TITLE
mpi4py installation with a concrete MPI implementation using pip

### ISSUE THREAD

**Issue by YarShev** [mpi4py/mpi4py#381]
I wonder if it is possible to install mpi4py (from source or PyPI - like `pip install mpi4py[mpich]`) with a concrete MPI implementation, for example, MPICH or OpenMPI, as it is possible with conda ([link](https://mpi4py.readthedocs.io/en/latest/install.html#using-conda))? If it hasn't been implemented yet, maybe we should consider this?

**Comment by dalcinl** [comment]
Well,  everything is technically possible. But there are issues and compromises to sort out. So far, MPI is an API and not an ABI (that may change in then upcoming MPI-5). MPICH and derivatives do support ABI compatibility between them. Therefore, mpi4py should support at least MPICH and Open MPI. But then what versions of those exactly? Arguably, we would need MPICH v3.x and v4.x, and Open MPI v4.x and v5.x (not yet released). This is because the next thing will happen is that users will request for these builds to be able to run with system-wide MPI installations available in HPC infrastrucutre via LD_LIBRARY_PATH, and that's a totally reasonable request (that `conda-forge` explicitly supports).

So far so good... slightly complicated, although I know how to do it. But, besides not having the time, there is nothing new or challenging or exiting to the task to justify doing if for free. I anyone going to commit to implement and more importantly maintain this for the foreseeable future? I don't want things to go this way: https://pypi.org/project/mpi4py-mpich/. This company solved their problems and needs by adding an entry in the Python Package Index, but they do not cared about alternative MPI implementations, or the MPICH version, not even to rebuild the package after mpi4py patch releases.

My current take on this is the following: Let's wait until MPI-5 have a stable ABI, and MPI implementations support it. Then we can upload manylinux and macos wheels that can work with any MPI implementation. In the mean time, conda and conda-forge already solve this problem. Private companies that need this should roll their own solution and publish packages in private PyPI servers, which is anyway good to prevent supply chain attacks. Also, private companies using conda that are not happy about the performance of conda-forge packages can still create an anaconda.org account and upload their own package builds for their own private consumption.

**Comment by YarShev** [comment]
I agree, this totally makes sense to me. Let's wait for MPI to have a stable ABI and for MPI implementations to support it.
