### ISSUE TITLE
Next release? 4.0.0?

### ISSUE THREAD

**Issue by jakirkham** [mpi4py/mpi4py#386]
It looks quite a bit of work has been done since the last release 👏

Am curious if there's a rough idea as to when the next release might come out. No pressure though (can see there's a lot of additions being included)

**Comment by dalcinl** [comment]
I've been waiting for weeks and months for Open MPI to release 5.0.0 with (partial) support for MPI 4.0.

**Comment by jakirkham** [comment]
Ah ok. That makes sense. Thanks for the context Lisandro! 🙏

Are there additional changes planned for mpi4py as part of this release or is it just\* a matter of upstream releases and testing?

\* - Recognizing there still may be considerable work to test and align

**Comment by dalcinl** [comment]
1. I have a branch with some minor utility additions to `mpi4py.futures` to help with the new support for parallel MPI tasks. This branch has not been merged yet because I not sure about the naming of the two utility functions I'm adding and, as usual, documentation has to be improved.
2. I'm working on producing binary wheels for all platforms and architectures, ready for `pip install`. This is a daunting task. I cannot just follow the simple approach of other wheel distributors, that is, shipping shared libraries within the wheel. I rather have to skip including MPI libraries, rely on users setting LD_LIBRARY_PATH, and support the combination of MPI 3.1/4.0 standard for MPICH/OpenMPI ABIs. I'm about to finish, but it took way more time than anticipated. Binaries are here: https://anaconda.org/mpi4py/repo. I still have to open a new Issue/Discussion to advertise this work and get feedback. I still have to test whether the binaries actually work in Cray (via `module load cray-mpich-abi`).

**Comment by jakirkham** [comment]
Thanks for the additional context! 🙏

**Comment by balay** [comment]
@dalcinl  perhaps consider `3.2` release - for `cython-3` changes for now?

One reason for this is to have a compatible mpi4py with `petsc4py@3.20` - thats scheduled for sept end.

**Comment by dalcinl** [comment]
@balay I'm considering making a new mpi4py release 3.1.5 to support Python 3.12. In the process, I will bound the Cython dependency below 3.0.0. The tarball will ship with fresh Cython-generated C sources, as it always did. But I'll not be updating the Cython *.pyx sources for Cython 3. I don't think my plan will affect spack, although I may be messing something.

**Comment by balay** [comment]
>  I don't think my plan will affect spack, although I may be messing something.

@dalcinl As per discussion at https://github.com/spack/spack/pull/36406#discussion_r1147956576
Spack install of petsc4py, [and then slepc4py, mpi4py] now always use cython dependency and cythonze in in the buid step - even if the generated cython sources exist in the tarball

**Comment by balay** [comment]
I guess with this major change in cython@3 - we should just revert those changes in spack and use generated cython sources - at-least for mpi4py -i.e revert https://github.com/spack/spack/pull/36460 -  [and avoid cython dependency in mpi4py spack spec - that can cause conflict with cython dependency in petsc4py etc..]

cc: @adamjstewart

**Comment by balay** [comment]
@dalcinl how does petsc4py handle mpi4py dependency? 

A simpler fix for the petsc4py/mpi4py/cython dependency conflict  issue is to add in the ability to disable mpi4py dependency [from petsc4py] - when needed.

**Comment by dalcinl** [comment]
petsc4py does not depend explicitly on mpi4py, otherwise MPIUNI in Python would not be possible. It has been like that for more than 15 years.

**Comment by balay** [comment]
I see libensemble has a dependency on mpi4py - so my alternate change might not help

**Comment by balay** [comment]
If using 'pre-genereated' cython sources is the preferred mode to deal with cython version issues - should we include them in petsc4py tarballs as well?

**Comment by balay** [comment]
And will there be a conflict with mixing numpy, mpi4py, petsc4py  etc - that are generated with different cython versions? [pre 3.0, and post-3.0?]

**Comment by dalcinl** [comment]
No, it is not the preferred mode for Cython 3 and onwards. mpi4py current release branch 3.1.x is stuck in the past because I don't want to make a mess. I should have released a new mpi4py 4.0.0  months ago, but I've been waiting for Open MPI to get 5.0.0 out, as Open MPI had been the number one reason of mpi4py failures for end users.

> And will there be a conflict with mixing numpy, mpi4py, petsc4py etc - that are generated with different cython versions? [pre 3.0, and post-3.0?]

I cannot speak for numpy, you will have to ask its developers. Regarding mpi4py/petsc4py, to the best of my knowledge, everything should be compatible. Had you ever have any incompatibility report between mpi4py/petsc4py? I bet your answer will be no. Do you think that's just by luck? You should stop worrying, I do care about backward compatibility and not messing with my users.

**Comment by dalcinl** [comment]
In the meantime, I published a new release 3.1.5 to address the Cython and Python 3.12 compatibility. 
Regarding NumPy 2.0, looks like aa8ae283b77663c0acf518681f206e9adadd4544 was all what mpi4py needed to fix.

**Comment by jakirkham** [comment]
Thanks Lisandro! 🙏

Nice to see NumPy 2.0 support looks straightforward in `mpi4py`

**Comment by matrosoe** [comment]
Hi there,

I've just been trying to run "from mp4py import MPI" and am getting
"python3.11/site-packages/mpi4py/MPI.cpython-311-x86_64-linux-gnu.so: undefined symbol: ompi_mpi_logical8"
I have mpi4py 3.1.5, python 3.11.5 and cython  3.0.2.

Is mpi4py 3.1.5 compatible with cython  3.0.2? I'm running other package that require cython 3.0.2 so unfortuneatly can't downgrade my cython. I read previously that that there was version of mpi4py that worked with cython 3. Is this available anywhere?

Thanks very much in advance.

**Comment by dalcinl** [comment]
> I've just been trying to run "from mp4py import MPI" and am getting
> "python3.11/site-packages/mpi4py/MPI.cpython-311-x86_64-linux-gnu.so: undefined symbol: ompi_mpi_logical8"

You provided very little information about your system, therefore I'll assume you are using some Open MPI version as your backend MPI implementation.

Your issue seems to be Open MPI problem, totally unrelated to mpi4py, Python, or Cython. 

Look what I have in my local Open MPI install
```
$ grep -A 2 OMPI_HAVE_FORTRAN_LOGICAL8 -r /home/devel/mpi/openmpi/main/include/mpi.h 
#define OMPI_HAVE_FORTRAN_LOGICAL8 1

/* Whether we have FORTRAN INTEGER*1 or not */
--
#if OMPI_HAVE_FORTRAN_LOGICAL8
#define MPI_LOGICAL8 OMPI_PREDEFINED_GLOBAL(MPI_Datatype, ompi_mpi_logical8)
#endif

$ nm /home/devel/mpi/openmpi/main/lib/libmpi.so | grep ompi_mpi_logical8
000000000050d2c0 D ompi_mpi_logical8
0000000000504ac8 D ompi_mpi_logical8_addr
```

As you can see, the `mpi.h` header advertises support for Fortran `MPI_LOGICAL8` is available, and the MPI shared library indeed have the `ompi_mpi_logical8` symbol.
Most likely, if you try something similar in your system, my guess is that things will be different. `mpi.h` will say that `MPI_LOGICAL8` is available, but the symbol in missing from the MPI shared library.
I hope you understand mpi4py is not responsible for such inconsistency.

Another possibility is that you are using an Open MPI installation different that the one used to originally build Open MPI. This may happen if a  mpi4py wheel is in the pip cache, you should run `pip cache remove mpi4py`, uninstall mpi4py, and install it again.

> Is mpi4py 3.1.5 compatible with cython 3.0.2? 
The mpi4py release tarball 3.1.5 does not actually require Cython to build. Even if you forcibly run Cython on it, I expect it to work (albeit with a lot of warnings that you can ignore), but I may be wrong.

PS: The 4.0.0 release has been delayed for quite a bit, I really have to get it out.

**Comment by dalcinl** [comment]
Closed via https://github.com/mpi4py/mpi4py/releases/tag/4.0.0
