### ISSUE TITLE
ranks the same for all processes

### ISSUE THREAD

**Issue by JaredKeithAveritt** [mpi4py/mpi4py#428]
I am running your code to fix my issue, and my output is not as expected: 
(TorchANI) [jarkeith@c-203-21 mpi4py]$ mpiexec -n 88 python -m mpi4py.futures hello2.py
Hello, World! I am worker 0 of 1 on c-203-21.
Hello, World! I am worker 0 of 1 on c-203-21.
Hello, World! I am worker 0 of 1 on c-203-21.
.
(39 lines removed)
.
Hello, World! I am worker 0 of 1 on c-203-21.
Hello, World! I am worker 0 of 1 on c-203-21.
Hello, World! I am worker 0 of 1 on c-203-22.
Hello, World! I am worker 0 of 1 on c-203-22.
Hello, World! I am worker 0 of 1 on c-203-22.
.
(39 lines removed)
.
Hello, World! I am worker 0 of 1 on c-203-22.
Hello, World! I am worker 0 of 1 on c-203-22.

I am using the code from a closed issue :
            

Let's use as an example the following parallel *Hello World!* using `mpi4py.futures`.
```python
from mpi4py import MPI
from mpi4py.futures import MPIPoolExecutor, wait

def helloworld():
    MPI.COMM_WORLD.Barrier()
    size = MPI.COMM_WORLD.Get_size()
    rank = MPI.COMM_WORLD.Get_rank()
    name = MPI.Get_processor_name()
    return f"Hello, World! I am worker {rank} of {size} on {name}."

if __name__ == '__main__':
    executor = MPIPoolExecutor(5)
    num_workers = executor._max_workers
    futures = []
    for _ in range(num_workers):
        f = executor.submit(helloworld)
        futures.append(f)
    wait(futures)
    for f in futures:
        print(f.result())
    executor.shutdown()
```
Now execute it with just one MPI process as usual, the executor will use 5 workers.
```
$ mpiexec -n 1 python helloworld.py
Hello, World! I am worker 0 of 5 on localhost.
Hello, World! I am worker 1 of 5 on localhost.
Hello, World! I am worker 2 of 5 on localhost.
Hello, World! I am worker 3 of 5 on localhost.
Hello, World! I am worker 4 of 5 on localhost.
```

_Originally posted by @dalcinl in https://github.com/mpi4py/mpi4py/issues/324#issuecomment-1462462621_

**Comment by dalcinl** [comment]
Things improved slightly since that comment, see the [development documentation](https://mpi4py.readthedocs.io/en/latest/mpi4py.futures.html#parallel-tasks) and the related [example](https://mpi4py.readthedocs.io/en/latest/mpi4py.futures.html#cpi-py).

I believe the reason your example is not working is because you are using `mpiexec -n 88 python -m mpi4py.futures helloworld.py`, while in my comment I used `mpiexec -n 1 python helloworld.py`. The second form uses MPI spawn, without that, the whole thing does not work.

If you are willing to use mpi4py from git master branch, then you can follow the example I linked above. Otherwise, you have to use the MPI spawn form, exactly as I stated in my original comment in #324.

**Comment by dalcinl** [comment]
BTW, just in case... Did you make sure your `mpiexec` corresponds to the same MPI implementation used to build and install mpi4py? Beware of the [pip cache](https://mpi4py.readthedocs.io/en/stable/install.html#using-pip)!

**Comment by JaredKeithAveritt** [comment]
Thanks!

I went and uninstalled mpi4py by using 

pip uninstall mpi4py
conda remove mpi4py 

then I installed it using : env MPICC=/nas/longleaf/apps-dogwood/mpi/gcc_11.2.0/openmpi-4.0.1 python -m pip install mpi4py

now my code gives: 
(TorchANI) [jarkeith@c-201-23 mpi4py]$ mpirun -n 1 python -m mpi4py.futures hello2.py
[c-201-23:16528] pml_ucx.c:285  Error: UCP worker does not support MPI_THREAD_MULTIPLE
Hello, World! I am worker 0 of 1 on c-201-23.
Hello, World! I am worker 0 of 1 on c-201-23.
Hello, World! I am worker 0 of 1 on c-201-23.
Hello, World! I am worker 0 of 1 on c-201-23.
Hello, World! I am worker 0 of 1 on c-201-23.

**Comment by dalcinl** [comment]
That is not the way to install the in-development version from the GitHub repository. 

* If you want to install inside a conda environment, then run `conda install openmpi-mpicc`, thay will setup the MPI compiler wrappers that will be used to compile C code using MPI. There should be no need to set `MPICC`, mpi4py should find the `mpicc` command automatically.
* As explained [here](https://github.com/mpi4py/mpi4py/blob/master/INSTALL.rst#using-pip), to install the in-development mpi4py, you have to invoke pip the following way:
```
python -m pip install https://github.com/mpi4py/mpi4py/tarball/master
```
* I see a warning related to stuff not supported with `MPI_THREAD_MULTIPLE`. If you have trouble running, perhaps you should set the environment variable `MPI4PY_RC_THREAD_LEVEL=serialized` and `mpi4py.futures` should take care of doing things properly.

PS: Your messages are a bit hard to read. Please remember to [enclose your code/output blocks with triple-backticks](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) to help readability.

**Comment by JaredKeithAveritt** [comment]
> That is not the way to install the in-development version from the GitHub repository. 
> 
> 
> 
> * If you want to install inside a conda environment, then run `conda install openmpi-mpicc`, thay will setup the MPI compiler wrappers that will be used to compile C code using MPI. There should be no need to set `MPICC`, mpi4py should find the `mpicc` command automatically.
> 
> * As explained [here](https://github.com/mpi4py/mpi4py/blob/master/INSTALL.rst#using-pip), to install the in-development mpi4py, you have to invoke pip the following way:
> 
> ```
> 
> python -m pip install https://github.com/mpi4py/mpi4py/tarball/master
> 
> ```

Thanks! I now deleted the old install of mpi4py and reinstalled with: 
```
python -m pip install --no-cache-dir https://github.com/mpi4py/mpi4py/tarball/master 
```

> * I see a warning related to stuff not supported with `MPI_THREAD_MULTIPLE`. If you have trouble running, perhaps you should set the environment variable `MPI4PY_RC_THREAD_LEVEL=serialized` and `mpi4py.futures` should take care of doing things properly.
> 
> 
> 

```
When I perform the test mentioned in the documentation, I get the error:
```
$ mpiexec -n 5 python -m mpi4py.bench helloworld
[c-203-23:25837] pml_ucx.c:285  Error: UCP worker does not support MPI_THREAD_MULTIPLE
[c-203-23:25833] pml_ucx.c:285  Error: UCP worker does not support MPI_THREAD_MULTIPLE
[c-203-23:25835] pml_ucx.c:285  Error: UCP worker does not support MPI_THREAD_MULTIPLE
[c-203-23:25836] pml_ucx.c:285  Error: UCP worker does not support MPI_THREAD_MULTIPLE
[c-203-23:25834] pml_ucx.c:285  Error: UCP worker does not support MPI_THREAD_MULTIPLE
Hello, World! I am process 4 of 5 on c-203-23.
Hello, World! I am process 0 of 5 on c-203-23.
Hello, World! I am process 2 of 5 on c-203-23.
Hello, World! I am process 3 of 5 on c-203-23.
Hello, World! I am process 1 of 5 on c-203-23.
```

But when I set the env variable and (without the mpi4py.futures) with the code -- I get the expected output: 
```
$ export MPI4PY_RC_THREAD_LEVEL=serialized 
$ mpiexec -n 5 python -m mpi4py.bench helloworld
Hello, World! I am process 0 of 5 on c-203-23.
Hello, World! I am process 2 of 5 on c-203-23.
Hello, World! I am process 4 of 5 on c-203-23.
Hello, World! I am process 3 of 5 on c-203-23.
Hello, World! I am process 1 of 5 on c-203-23.
```

but this is where things are weird again, when I run with the same environment variable as before (MPI4PY_RC_THREAD_LEVEL=serialized ) and with mpi4py.futures module for the code in the original post (which was from your original comment in https://github.com/mpi4py/mpi4py/issues/324) : 
```
$ mpiexec -n 1 python -m mpi4py.futures hello2.py
Hello, World! I am worker 0 of 1 on c-203-23.
```
I would expect there to be 5 workers and size of 5.

**Comment by dalcinl** [comment]
> ```
> $ mpiexec -n 1 python -m mpi4py.futures hello2.py
> 
> Hello, World! I am worker 0 of 1 on c-203-23.
> ```
> 
> I would expect there to be 5 workers and size of 5.

If you use `python -m mpi4py.futures script.py` (instead of just  `python script.py`), then you have to ask mpiexec for *n+1* processes! Therefore, you have to execute:
```
$ mpiexec -n 6 python -m mpi4py.futures hello2.py
```
Then you should see output from workers 0,1,2,3,4. The "missing" process is actually the master processes, you cannot avoid that, that's the way `mpi4py.futures` works, one process has to be the master, and you have to account for it.
In this case, mpi4py.futures is not using MPI spawn. All processes are started in advance via `mpiexec`, and `mpi4py.futures` splits them in one master and *n* workers. Please read the [documentation](https://mpi4py.readthedocs.io/en/latest/mpi4py.futures.html#command-line) for further details.

Let me insist: When you use `-m mpi4py.futures`, things work different. You have to launch *n+1* processes with `mpiexec`. If you DO NOT use `-m mpi4py.futures`, then just launch one process (the master, with `mpiexec -n 1 ...` ) and `mpi4py.futures` will spawn *n* additional worker processes at runtime. Maybe you should consider not passing the number of workers in the script (i.e 5 in the example above), and instead set the environment variable [`MPI4PY_FUTURES_MAX_WORKERS`](https://mpi4py.readthedocs.io/en/latest/mpi4py.futures.html#envvar-MPI4PY_FUTURES_MAX_WORKERS) to the desired number of workers. This approach may prove to be more flexible, although it is a matter of taste.

**Comment by dalcinl** [comment]
@JaredKeithAveritt Is it all clear now? Can we close this issue?
