### ISSUE TITLE
scount/rcount no longer work as np.arrays

### ISSUE THREAD

**Issue by s-valent** [mpi4py/mpi4py#430]
Hi! 

I noticed that Scatterv and possibly other functions no longer accept np.arrays as their scount/rcount arguments in master branch.

<details><summary>Example</summary>
<p>

```python
#!/usr/bin/env mpiexec -n 3 python

import numpy as np
from mpi4py import MPI

comm = MPI.COMM_WORLD
assert comm.size == 3

amounts = np.array([3, 4, 2])  # | works as lists
offsets = np.array([0, 3, 7])  # |

if comm.rank == 0:
    data = np.arange(sum(amounts), dtype=float)
else:
    data = None

buffer = np.empty(amounts[comm.rank], dtype=float)

comm.Scatterv(
    [data, amounts, offsets, MPI.DOUBLE],
    [buffer, amounts[comm.rank], MPI.DOUBLE],
    root=0
)

print(f"{comm.rank}, {buffer =}")
```

</p>
</details>

It broke from #356, when function is_integral in src/mpi4py/MPI/msgbuffer.pxi was replaced with PyIndex_Check.
Is it intentional, or can we bring it back?

**Comment by dalcinl** [comment]
> Is it intentional, or can we bring it back?

No, it was not intentional. I need time to investigate. It could be than the proper fix should go to NumPy. You have to agree with me that the  previous implementation of `is_integral` made absolutely no sense, and you would have to navigate quite a bit of core Python and NumPy code to understand why it was that way.
