### ISSUE TITLE
intel one api with mpi4py

### ISSUE THREAD

**Issue by Ying-Zi66** [mpi4py/mpi4py#432]
I want to use mpi in python so i install mpi4py.I have installed intel oneapi.After I installed mpi4py,the anaconda prompt shows
C:\Users\WL>if defined CONDA_BUILD_STATE ()

C:\Users\WL>if exist "C:\Windows\System32\msmpi.dll" (
echo "You seem to have a system wide installation of MSMPI. "
 echo "Due to the way DLL loading works on windows, system wide installation "
 echo "will probably overshadow the conda installation. Uninstalling "
 echo "the system wide installation and forced deleting C:\Windows\System32\msmpi*.dll"
 echo "will help, but may break other software using the system wide installation."
)
"You seem to have a system wide installation of MSMPI. "
"Due to the way DLL loading works on windows, system wide installation "
"will probably overshadow the conda installation. Uninstalling "
"the system wide installation and forced deleting C:\Windows\System32\msmpi*.dll"
"will help, but may break other software using the system wide installation."
How to diappear these messages?

**Comment by Ying-Zi66** [comment]
I cant use mpi4py 

from mpi4py import MPI

comm = MPI.COMM_WORLD
rank = comm.Get_rank()

if rank == 0:
    data = {'a': 7, 'b': 3.14}
    comm.send(data, dest=1, tag=11)
elif rank == 1:
    data = comm.recv(source=0, tag=11)

runfile('C:/Users/WL/.spyder-py3/temp.py', wdir='C:/Users/WL/.spyder-py3')
Traceback (most recent call last):

  File E:\Program Files\anaconda3\Lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\wl\.spyder-py3\temp.py:14
    comm.send(data, dest=1, tag=11)

  File mpi4py\MPI\Comm.pyx:1406 in mpi4py.MPI.Comm.send

  File mpi4py\MPI\msgpickle.pxi:212 in mpi4py.MPI.PyMPI_send

Exception: Invalid rank, error stack:
MPI_Send(buf=0x0000019561012420, count=35, MPI_BYTE, dest=1, tag=11, MPI_COMM_WORLD) failed
Invalid rank has value 1 but must be nonnegative and less than 1

**Comment by dalcinl** [comment]
You did not disclose how exactly you installed Intel MPI and mpi4py. Issue reports should have complete information about how users do things, otherwise maintainers cannot possibly know what's going on.

If you are installing things in a conda environment, then follow the instructions in https://github.com/conda-forge/mpi4py-feedstock/issues/67#issuecomment-1822495025. Please note than in this case Intel MPI will be used from the copy intalled in the conda environment, and not from any other location.

Another alternative is to install Intel MPI externally at the system level (Is this that you did?), and then use pip to install mpi4py as instructed here: https://github.com/mpi4py/mpi4py-publish.
