### ISSUE TITLE
Does mpi4py work over a WAN?

### ISSUE THREAD

**Issue by linjian-tech** [mpi4py/mpi4py#443]
We have successfully implemented two nodes communicating with each other in our LAN. However, when we set both node ip to WAN ip, the client cannot connect to the server (ERROR MESSAGE: HYDU_sock_connect (utils/sock/sock.c:143): unable to connect from "node5" to "node5" (Connection refused) [proxy:0:1@node5] main (pm/pmiserv/pmip.c:181): unable to connect to server node5 at port 46135 (check for firewalls!)）). Can you help us with this, thanks!

**Comment by dalcinl** [comment]
This issue has nothing to do with mpi4py, but with the backend MPI (in your case MPICH). Therefore, you have to read MPICH's documentation about how to properly configure nodes for remote access/login. If you cannot make it work, I'm afraid your will have to ask to MPICH devs. All that being said, and from the error message, maybe the problem is indeed related to a firewall running in the node, blocking access to a port required by the Hydra process manager. Maybe you have to allow access to a port range in your firewall, and then use the `MPICH_PORT_RANGE` environment variable to specify the port range. Again, check MPICH documentation for all the details.
