### ISSUE TITLE
AttributeError: module 'mpi4py' has no attribute 'MPI'

### ISSUE THREAD

**Issue by Lanbai-eleven** [mpi4py/mpi4py#447]
I have tried on both windows and ubuntu to run a fedml code which depended on MPI4PY
And i'm sure i have installed msmpi or openmpi but when i run always get the error:
module 'mpi4py' has no attribute 'MPI'
And i see the mpi4py folder under my conda, there is no MPI folder which i can see in src:
![image](https://github.com/mpi4py/mpi4py/assets/64012355/e50cef8d-3f3e-4808-aaca-fd51f936b13c)

**Comment by dalcinl** [comment]
On Windows, you have to look at `MPI.*.pyd` files, and you have one there, but corresponds to a Python 3.8 build. Your issue report did not include any additional information about what Python version you are using, how you installed it, and how you installed mpi4py. Please submit a proper report with additional information about your installation. Screenshots of foleder contents are not very informative.

**Comment by Lanbai-eleven** [comment]
I'm sorry for not providing more details in my previous inquiry. Here are the specific installation steps I followed and additional information:
First i try use mpi4py on windows, python version is 3.8.1, and i follow the steps as:
1. install msmpi and sdk from [here](https://www.microsoft.com/en-us/download/details.aspx?id=105289), and confirm that it has been added to the system PATH.
2. create a new conda environment and install mpi4py, i use both **pip install** and **conda install** in different attempts

on Ubuntu 20.04，I try almost the same operations：
1. first **sudo apt-get install libopenmpi-dev**
2.  create a new conda environment and install mpi4py， also try installed from pip or conda

But the structure of all the attempts mentioned above resulted in this error message：AttributeError: module 'mpi4py' has no attribute 'MPI‘



> On Windows, you have to look at `MPI.*.pyd` files, and you have one there, but corresponds to a Python 3.8 build. Your issue report did not include any additional information about what Python version you are using, how you installed it, and how you installed mpi4py. Please submit a proper report with additional information about your installation. Screenshots of foleder contents are not very informative.

**Comment by dalcinl** [comment]
Oh, you are getting `AttributeError`, not `ImportError`. I think I know what's going on. You did not provide an actual code reproducer, otherwise I would have figured it out immediately. 

The usual way to use mpi4py is to import the `MPI` module form the top level `mpi4py` namespace, the following way

```python
from mpi4py import MPI
```
And from there you access the `MPI` module.

What you CANNOT do is the following:
```python
>>> import mpi4py
>>> mpi4py.MPI
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'mpi4py' has no attribute 'MPI'
```
because at that point the `MPI` module has not been imported yet.

What would work instead is the following:
```python
>>> import mpi4py.MPI
>>> mpi4py.MPI
<module 'mpi4py.MPI' (<_frozen_importlib_external.NamespaceLoader object at 0x107a68610>)>
```
but writing `mpi4py.MPI` as a namespace prefix every time is a bit tedious. Therefore, the recommended style is as the first example above.

**Comment by Lanbai-eleven** [comment]
Oh! Thank you very much for your help, I have solved my problem  by following your guidance! The error appeared in another ready-made library fedml, which I used. I don't know how they managed not to report an error :joy:.


> 哦，你得到了`AttributeError`，不是`ImportError`。我想我知道发生了什么事。您没有提供实际的代码重现器，否则我会立即弄清楚。
> 
> 使用 mpi4py 的通常方法是从`MPI`顶级`mpi4py`命名空间导入模块，如下所示
> 
> ```python
> from mpi4py import MPI
> ```
> 
> 从那里您可以访问该`MPI`模块。
> 
> 您不能执行以下操作：
> 
> ```python
> >>> import mpi4py
> >>> mpi4py.MPI
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> AttributeError: module 'mpi4py' has no attribute 'MPI'
> ```
> 
> 因为此时该`MPI`模块尚未导入。
> 
> 相反，可行的方法如下：
> 
> ```python
> >>> import mpi4py.MPI
> >>> mpi4py.MPI
> <module 'mpi4py.MPI' from '<redacted>/mpi4py/MPI.cpython-311-darwin.so'>
> ```
> 
> 但`mpi4py.MPI`每次都写成命名空间前缀有点乏味。因此，推荐的样式如上面第一个例子。

**Comment by dalcinl** [comment]
> The error appeared in another ready-made library fedml, which I used. I don't know how they managed not to report an error 😂.

This is probably because the authors usually do the `import mpi4py.MPI` thing at the very beginning of the Python run, before the `mp4py.MPI` attribute access. But now that you used it, you followed slightly different conventions, and then things break down. I would suggest you report your troubles back to the @FedML-AI folks for them to be aware of this issue.
