### ISSUE TITLE
Some suggestions for the pip installation page of the guide!

### ISSUE THREAD

**Issue by Maheng123** [mpi4py/mpi4py#515]
Before using pip install mpi4py in the guide, it is recommended to suggest using conda install openmpi to build the MPI environment. After that, conda install mpi4py can be used to smoothly install the mpi4py library and ensure it runs correctly.

This approach helps avoid compatibility issues between different versions of Python, OpenMPI, and mpi4py.

**Comment by dalcinl** [comment]
Can you link the exact file and line within the repository in the master branch that you are complaining about?

**Comment by dalcinl** [comment]
This section clearly instructs how to install mpi4py + the MPI implementation of choice: https://github.com/mpi4py/mpi4py/blob/master/INSTALL.rst#using-conda

In the `INSTALL.rst` file, the instructions about using pip come first simply because pip is the de-facto standard Python-specific package manager. I expect any conda user to know that they should prefer conda over pip, and use pip only if a conda package is not available.

**Comment by Maheng123** [comment]
I sincerely apologize for not finding the webpage you provided right away. What I found is this webpage: https://mpi4py.readthedocs.io/en/stable/install.html. According to its instructions, it seems that I need to download the program from the OpenMPI official website and create an environment. However, this leads to the mpi4py library not being able to run the program properly.
