### ISSUE TITLE
Ctrl+C Keyboard interrupts are not passed on to Python

### ISSUE THREAD

**Issue by jjacobowitz** [mpi4py/mpi4py#522]
When running mpi code with `mpirun`, keyboard interrupts are not passed on to Python. The interrupt simply ends the process(es).

Consider this example code:

```
from mpi4py import MPI
 
def f(i):
    # raise KeyboardInterrupt()
    return i**0.5

if __name__ == "__main__":
    comm = MPI.COMM_WORLD
    rank = comm.Get_rank()
    size = comm.Get_size()
    print(rank, size)
    
    try:
        for i in range(1_000_000):
            print(f(i))
    except KeyboardInterrupt:
        print("keyboard interrupt caught")
```

If the keyboard interrupt in `f` is uncommented, the code will capture the interrupt whether it is run using `python file.py` or `mpirun -np 1 python file.py`. But, if that line remains commented, entering Ctrl+C while the code is running will not trigger the exception when run using `mpirun -np 1 python file.py`.

I found a [Stackoverflow post](https://stackoverflow.com/questions/58117400/mpiexec-python-c-del-method-not-executed-and-no-traceback) that suggested using the Python `signal` module and adding a trigger for `signal.SIGTERM`, but this also does not capture the interrupt (see example code below).

```
from mpi4py import MPI
import signal

def sigterm_handler(signum, frame):
    print("here")
    raise KeyboardInterrupt

signal.signal(signal.SIGTERM, sigterm_handler)

def f(i):
    # raise KeyboardInterrupt()
    return i**0.5
        
if __name__ == "__main__":
    comm = MPI.COMM_WORLD
    rank = comm.Get_rank()
    size = comm.Get_size()
    print(rank, size)
    
    try:
        for i in range(1_000_000):
            print(f(i))
    except KeyboardInterrupt:
        print("keyboard interrupt caught")
```

The contrived example above is similar to my [Stackoverflow post](https://stackoverflow.com/q/78779650/12131013) on the problem where I have a context manager that is not exited properly after entering Ctrl+C, which can be an issue depending on what the context manager is managing.

The expected functionality would be that a keyboard interrupt while running the code in MPI would be passed on to Python for exception handling, or there should be some sort of signal sent to Python that can be used to trigger exit/cleanup processes.

**Comment by dalcinl** [comment]
What is happening here is that the runtime components (mpirun/mpiexec) of your backend MPI is not forwarding the signal to the MPI processes. This is definitely not mpi4py's fault, nor mpi4py can do anything about it. What MPI implementation and version, and OS or Linux distribution are you using? That's an essential piece of information you are not providing. 

I just tested things with MPICH 4.2.2 from Fedora 40, and things work fine, `mpiexec` do forward the SIGINT signal to the Python processes. In MPICH's `mpiexec` implementation, the first time Crtl+C is pressed, the MPI processes are signaled with SIGINT (which Python maps to raising KeyboardInterrupt). If you press Crtl+C a second time, then `mpiexec` takes over forcibly abort the parallel run.

**Comment by jjacobowitz** [comment]
Here are the versions on my system:
```
python: 3.10.14
mpirun/mpiexec: 4.1.4
mpi4py: 3.1.6
Ubuntu: 22.04.4 LTS
```

**Comment by dalcinl** [comment]
Yes, the problem is indeed Open MPI. It seems that Open MPI, rather than just forwarding SIGINT and let the MPI process/es decide how to handle it, it just kills the MPI process/es.

Looks like this behavior (killing on SIGINT) is explicitly documented here:
https://docs.open-mpi.org/en/v5.0.x/man-openmpi/man1/mpirun.1.html#signal-propagation
although there is an admonition warning that the documentation is old.

Also, there is some support for signal forwarding, documented here:
https://docs.open-mpi.org/en/v5.0.x/man-openmpi/man1/mpirun.1.html#the-forward-signals-option
but if you try to use it, `mpiexec` will reject the option `--forward-signals SIGINT`.

As much as I do not like this way of handling SIGINT and consider it a misfeature, there is absolutely nothing mpi4py can do to workaround the problem.  You should raise your concerns and complaints to the Open MPI community.
