### ISSUE TITLE
Segmentation fault, Signal 11, on any MPI job on Linux HPC systems

### ISSUE THREAD

**Issue by yonghoonlee** [mpi4py/mpi4py#523]
mpi4py version 3.1.6 creates segmentation fault (signal 11) problem on Linux.
The problem is consistent on various Linux environments, including:

HPC with Intel Xeon + RHEL 8.8 (HPE Cray) + Slurm + Miniforge 3 (`conda install mpi4py`)
HPC with AMD EPYC + Rocky Linux 8.8 + Slurm + Miniforge 3 (`conda install mpi4py`)
Personal Linux desktop with Intel Core i7 + Ubuntu 22.04 LTS + `mpirun -np 10 python ...` + Miniforge 3 (`conda install mpi4py`)

The problem is resolved after downgraded to mpi4py version 3.1.5.

However, mpi4py 3.1.6 installed on

Apple M3 Max + macOS Sonoma + `mpirun -np 10 python ...` + Miniforge 3 ('conda install mpi4py')

environment did not show the segmentation fault problem. It was okay.

**Comment by dalcinl** [comment]
If you look at the code diff between 3.1.6 and 3.16: https://github.com/mpi4py/mpi4py/compare/3.1.5...3.1.6
then you should agree that these differences are minimal, and then cannot really explain a segmentation fault.

You did not mention what backend MPI you are using. Also, where is the minimal code reproducer to debug the issue? I'm inclined to say that this is not really an mpi4py bug, but the two different mpi4py versions pulling in different versions of its dependencies, including MPI. 

At this point I think you should raise an issue in the conda-forge/openmpi-feedstock repository, and provide precise instructions about how you built your conda environment (conda install command you are using), alongside with some minimal code able to reproduce the segmentation fault.

As I have no evidence that this problem is related to an mpi4py code bug, I'm closing the issue for the time being.

**Comment by yonghoonlee** [comment]
@dalcinl Thank you for clarification. I will check other dependencies for further investigation. What I did was to create conda environments just including mpi4py 3.1.5 and 3.1.6 and conda installed all dependencies including mpi. So, I agree. Associated mpi version or other dependencies might be creating this segmentation fault. Thank you.
