### ISSUE TITLE
Conda package compatible with Python 3.12

### ISSUE THREAD

**Issue by hdante** [mpi4py/mpi4py#529]
Hello, the current mpi4py package from the official conda repository won't install on a clean conda environment (using python 3.12):

```
$ conda install -y mpi4py
Channels:
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: - warning  libmamba Added empty dependency for problem type SOLVER_RULE_UPDATE
failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package mpi4py-3.0.3-py27h028fd6f_0 requires python >=2.7,<2.8.0a0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ mpi4py is installable with the potential options
│  ├─ mpi4py 3.0.3 would require
│  │  └─ python >=2.7,<2.8.0a0 , which can be installed;
│  ├─ mpi4py 3.0.3 would require
│  │  └─ python >=3.6,<3.7.0a0 , which can be installed;
│  ├─ mpi4py [3.0.3|3.1.4] would require
│  │  └─ python >=3.7,<3.8.0a0 , which can be installed;
│  ├─ mpi4py [3.0.3|3.1.4] would require
│  │  └─ python >=3.8,<3.9.0a0 , which can be installed;
│  ├─ mpi4py 3.1.4 would require
│  │  └─ python >=3.10,<3.11.0a0 , which can be installed;
│  ├─ mpi4py 3.1.4 would require
│  │  └─ python >=3.11,<3.12.0a0 , which can be installed;
│  └─ mpi4py 3.1.4 would require
│     └─ python >=3.9,<3.10.0a0 , which can be installed;
└─ pin-1 is not installable because it requires
   └─ python 3.12.* , which conflicts with any installable versions previously reported.
```

Is it possible to update it to support Python 3.12 ? Thanks,

**Comment by dalcinl** [comment]
Looks like you are using the Anaconda "defaults" channel. If you are a customer of the Anaconda Python distribution, ask them to provide proper packages for Python 3.12. Otherwise, start using packages from the conda-forge community. I myself maintain the conda-forge mpi4py package at https://github.com/conda-forge/mpi4py-feedstock. I also distribute MPI and mpi4py Python wheels at https://pypi.org/project/mpi4py/ and https://anaconda.org/mpi4py. Anything beyond these binary distribution of mpi4py is absolutely not my responsibility, therefore your issue does not belong here, sorry.

**Comment by hdante** [comment]
Hello, thank you for the explanation. I'll start trying to request an update on the `defaults` channel, to avoid a possible snowball effect on the installation's dependency packages when including `conda-forge`. In any case, I'll assume that the package in `conda-forge` is officially supported and switch to it if necessary.

Do you know where I should report the request to ? (for updating the `defaults` channel)

**Comment by dalcinl** [comment]
> Do you know where I should report the request to ? (for updating the `defaults` channel)

I'm not really sure, but perhaps here: https://github.com/ContinuumIO/anaconda-issues/issues.
