### ISSUE TITLE
SEGFAULT when importing mpi4py on HPC systems

### ISSUE THREAD

**Issue by MarzioVallero** [mpi4py/mpi4py#540]
I ran my tests on an HPC machine equipped with 1 32-core Intel Xeon Platinum 8358 CPU, 2.60GHz (Ice Lake) and 4 A100 GPUs.

I created a new miniconda environment with the command:
`conda create -n sirius test_env python=3.12 mpi4py`

I ran the following example code over a SLURM job with 2 tasks, making sure to purge all modules except for cuda/12.1:
`from mpi4py import MPI`
`comm = MPI.COMM_WORLD`
`rank = comm.Get_rank()`
`if rank == 0:`
`    data = {'key1' : [7, 2.72, 2+3j],`
`            'key2' : ( 'abc', 'xyz')}`
`else:`
`    data = None`
`data = comm.bcast(data, root=0)`

This first job terminated successfully.
I then installed the cuquatum and openmpi packages with the following command:
`conda install cuquantum openmpi`

which prompts me that these packages will be removed/updated:
_The following packages will be REMOVED:
  mpich-4.2.2-h4a7f18d_101
The following packages will be DOWNGRADED:
  mpi                                             1.0-mpich --> 1.0-openmpi 
  mpi4py                              4.0.0-py312h5924d30_1 --> 4.0.0-py312h1f2d5bd_1_

Once approving the update/removal, I re-ran the same example code as before, with the same SLURM job settings, and I get the error:
_[REDACTED] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x3ff00000001)_
_[REDACTED] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x3ff00000001)_
_--------------------------------------------------------------------------_
_prterun noticed that process rank 1 with PID 1708838 on node REDACTED exited on signal 11 (Segmentation fault)._
_--------------------------------------------------------------------------_

What can be the cause of this?

**Comment by dalcinl** [comment]
You should have submitted this issue so conda-forge/mpi4py-feedstock.

First, when you create your environment, you should do it this way, adding openmpi explicitly:
```
conda create -n sirius test_env python=3.12 mpi4py openmpi
```

Next, try to run your job again. This time mpi4py will use Open MPI. It may work or not. If it does not work, then I'm clueless. Maybe try to enable UCX, as in the comment here:
https://github.com/conda-forge/openmpi-feedstock/blob/main/recipe/post-link-ucx.sh

If the previous test works, move on and install cuquantum. To run GPU-aware MPI, make sure to set things up properly, look at the comments here:
https://github.com/conda-forge/openmpi-feedstock/blob/main/recipe/post-link-cuda.sh

**Comment by MarzioVallero** [comment]
Hello @dalcinl, sorry for having submitted on the wrong forum, and thanks for your quick reply.

I tried installing and activating UCX, with no success in running the previous example.
I could not use GPU-aware MPI, since the code I am to run also uses NCCL, which deadlocks if run together with CUDA-aware MPI.

Upon further investigation, I found out that the HPC system I am using comes with precompiled OpenMPI 4.1.6.
As such, I downgraded mpi4py=3.1.5, which runs on that version of OpenMPI, and everything worked.
I tried introducing conda-level environment variables that remap LD_LIBRARY_PATH and MPI_PATH so as to have them pointing to the OpenMPI implementations installed in the conda environment, with no success.
It seems that there is some hidden environment variable down the line of the SLURM context manager that forcibly links the precompiled OpenMPI, instead of that of the miniconda environment.
This is not a solution to my issue, but nonetheless the code works.

I would not know where to search exactly, but there is definitely something wrong down the hood, either in the miniconda installer/linker, or in the HPC shell environment I am using.
For what concerns me, this issue can be closed.

**Comment by dalcinl** [comment]
By design (that I do not like and I objected elsewhere), I believe the conda-forge binaries (in this case the mpi4py.MPI module) will not allow to change the MPI library via LD_LIBRARY_PATH. Thinks are hardwired such that everything you install in a conda-environment gets tightly coupled, to the point that LD_LIBRARY_PATH is no longer honored. Rationale: help beginners to not mess things up. My take: never ever favor beginners at the expense of professionals.
HOWEVER, after reading your comment, it is not clear to my if things in your system are behaving the way conda-forge intends, or the way I like. 

If the openmpi package from conda-forge does not work (you should try running some simple helloworld.c binary), then there is no point discussing it here in an mpi4py issue, the conda-forge/openmpi-feedstock is the appropriate place.
Then what you should try is running with the Open MPI installation in your HPC system, which I guess is already working. To that end, what you should do is installing in your conda environment the dummy "external" Open MPI package at the same version you have in your system (4.1.6).  It is as simple as
```console
conda create -n sirius python=3.12 mpi4py 'openmpi=4.1.6=external_*'
```
and now your environment does not really have openmpi installed, and mpi4py (and any other conda-forge package) is going to pick up the MPI you have in your system.
https://conda-forge.org/docs/user/tipsandtricks/#using-external-message-passing-interface-mpi-libraries

With this approach you could even attempt to use the NVIDIA openmpi build. Alternatively, you can also try installing mpi4py with pip, which will build from sources using your system MPI. Or you can pip-install pre-built MPI wheels from here: https://anaconda.org/mpi4py/mpi4py

**Comment by MarzioVallero** [comment]
At the moment, I do not know if this is an issue of conda-forge/openmpi, or an issue of conda-forge/mpi4py, although I agree with you: not honoring environment varaibles may definitely be the cause of all of this.

I am afraid I will have no time for testing on this HPC system for the time being, as the main concern was to get the code running, not finding out the reasons behind this issue (unfortunately).
I will try to get back to this and perfrom the tests you suggested.
In the meantime, I have no further questions or issues, thank you for your patience.
