### ISSUE TITLE
Communicators are not hashable

### ISSUE THREAD

**Issue by PhilipVinc** [mpi4py/mpi4py#558]
Hello.

For using them with `jax` , it would be useful if `mpi4py` communicator objects were hashable, such that we could pass them as static argument to their functions.

A simple hash implementation could be the default one, that returns their pointer address (id) which I believe should be correct.

Unfortunately they right now declare `__hash__=None` which in Python means "not hashable" . 
Is there a reason why they are declared as such?

**Comment by dalcinl** [comment]
I'd love to make communicators (and all other MPI objects) hashable. However, MPI objects are not strictly immutable, simply because you can `xxx.Free()` them,  and then the internal handle becomes `MPI_XXX_NULL`. As you may be very well aware, not respecting strict immutability would break Python hash tables, as shown in the following example:

```python
from mpi4py import MPI

class HashableIntracomm(MPI.Intracomm):
    def __hash__(self):
        return hash(self.handle)

comm1 = HashableIntracomm(MPI.COMM_SELF.Dup())
comm2 = HashableIntracomm(MPI.COMM_SELF.Dup())
commset = {comm1, comm2}
assert comm1 in commset
assert comm2 in commset
comm2.Free()
assert comm1 in commset
assert comm2 in commset  # this one fails!

null = HashableIntracomm(MPI.COMM_NULL)
assert comm2 == null
assert null in commset  # this one fails, too!
```

It is true that MPI objects, during their useful life (that is, before `Free()`ing them) are immutable. Therefore, it is really tempting to make them hashable anyway because such property is so useful. However, the realization that this may lead to really nasty bugs that would be really hard to debug, not to mention unforeseeable consequences related to Python's hash table implementation details (e.g. the use of cached hash values), had kept me away from my temptation to side on practicality.

By the way, the above example shows how to make a hashable communicator subclass to use under you own responsibility, that is, you have to guarantee that at the time you call `comm.Free()` the communicator object is no longer stored in any hash table that may get broken due to the internal `MPI_Comm` handle becoming `MPI_COMM_NULL`.

Another possibility is to use the `Comm.handle` attribute and the `Comm.fromhandle()` method to pass the comm via its integral handle and reconstruct the object within the function.

```python
from mpi4py import MPI

def function(commhandle):
    comm = MPI.Intracomm.fromhandle(commhandle)
    print(comm.rank, comm.size)

function(MPI.COMM_WORLD.handle)
```
```console
$ mpiexec -n 5 python handle.py 
0 5
1 5
2 5
3 5
4 5
```

Could any of the alternatives above work reasonably well with `jax`?

cc. @stefanozampini
