### ISSUE TITLE
MPI stub

### ISSUE THREAD

**Issue by battleoftwok** [mpi4py/mpi4py#582]
Is it planned to add a stub that emulates the behavior of MPI in one process (`mpiexec -n 1`)? Or is it already possible?

There are many similar implementations in C++ / Fortran:

- https://github.com/ssciwr/FakeMPI;
- https://github.com/scivision/mpi_stubs/tree/main;

**Comment by dalcinl** [comment]
I'm not sure I understood your request. mpi4py is just a wrapper, therefore it can be built with any sequential MPI stub implementation.
Beware that most sequential MPI stubs I know are not true MPI implementations. For example, they cannot send/recv-to-self.

**Comment by battleoftwok** [comment]
The stub needs to work the same as the original when running in a single process (`mpiexec -n 1`). How will `send` behave when running in one process? Is it being sent or not?

**Comment by battleoftwok** [comment]
I want to simulate the behavior of a peer-to-peer network when an attempt to import mpi4py fails.

**Comment by dalcinl** [comment]
> How will `send` behave when running in one process? Is it being sent or not?

I reiterate: mpi4py is a wrapper. When you do `comm.Send()` in Python, that eventually ends calling `MPI_Send()`. If you are using a sequential MPI stub, it is up to the developer of such stub what happens in `MPI_Send()` and it is not at all the responsibility of mpi4py.  You should elaborate on what kind of errors you are getting, otherwise I cannot even guess what could be the problem. Anyway, it is a safe bet for me to say that any issues are most likely not mpi4py's fault, but if you are a bit more detailed about the error, I may be able to offer additional insight.

**Comment by dalcinl** [comment]
No, I'm not aware of any "mpi4py stub". Note however that the usual way to handle optional dependencies in Python is to do something like the following:

```python
try:
    from mpi4py import MPI
exept ImportError:
    MPI = None
...
if MPI:
    # do things parallel using MPI
else:
    # do things sequentially without MPI
```

Another similar approach is to write a module with functions that take a communicator, and if the communicator is None do things sequentially, for example:
https://github.com/MathEXLab/PySPOD/blob/main/pyspod/utils/parallel.py#L161
https://github.com/MathEXLab/PySPOD/blob/main/pyspod/utils/parallel.py#L186

**Comment by battleoftwok** [comment]
Thank you!
