### ISSUE TITLE
Update conda release for easy environment builds

### ISSUE THREAD

**Issue by LysSanzMoreta** [mpi4py/mpi4py#583]
pip vs conda repositories are at different versions, could you update them?

Thanks!

**Comment by dalcinl** [comment]
I'm not sure what you mean. Can you elaborate?

https://pypi.org/project/mpi4py/4.0.1/
https://anaconda.org/conda-forge/mpi4py/files?version=4.0.1
https://anaconda.org/mpi4py/mpi4py/files?version=4.0.1

**Comment by dalcinl** [comment]
@LysSanzMoreta We are waiting for your clarifications.

**Comment by LysSanzMoreta** [comment]
@dalcinl Hi ,sorry for the delay

It is just that here it says that the latest is 3.1.4 https://anaconda.org/anaconda/mpi4py

So that is the one that is downloaded by default (unless you know by heart the version), if that makes sense

**Comment by dalcinl** [comment]
@LysSanzMoreta That version of mpi4py is completely outside of my control, as much or the versions that are available to users of the various Linux distributions and macOS Homebrew and MacPorts. 

The URL https://anaconda.org/anaconda/mpi4py corresponds to the Anaconda Python distribution, which is in the hands of a private company. You should ask them to upload a more recent mpi4py version. Otherwise, you can use the conda-forge channel, which is community-maintained (including myself) and usually have very up to date packages, including the latest mpi4py. Note however than when when you add the conda-forge channel, you may need to install other packages from there, too, such that everything is compatible each other. To use the conda-forge channel, just follow the instructions in their [documentation](https://conda-forge.org/docs/user/introduction/#how-can-i-install-packages-from-conda-forge).
