### ISSUE TITLE
Ipython Notebook in Vscode Crash

### ISSUE THREAD

**Issue by IsaacWarren** [mpi4py/mpi4py#592]
Issue in jupyter extension Repo: https://github.com/microsoft/vscode-jupyter/issues/16283

Reproducer:
```python
import mpi4py.MPI as MPI
comm_world = MPI.COMM_WORLD
comm_world.Spawn(
            # get the same python executable that is currently running
            "python", ["-c",  "import mpi4py.MPI as MPI; print(MPI.COMM_WORLD.Get_rank())"],
            1,
        )
```
Installed packages:
```
pip install mpi4py jupyter
pip install -i https://pypi.anaconda.org/mpi4py/simple mpich 
```
If the kernel is restarted after the reproducer is run in a cell the whole editor crashes. This seems to be because sending a SIGINT or SIGTERM to the child mpiexec process crashes the ipykernel and SIGTERM is sent to all child processes on kernel restart. If you have any insight into how to debug this further it would be greatly appreciated.

**Comment by dalcinl** [comment]
I have two comments:

1. You should use `sys.executable` instead of `python` to make sure you are using exactly the same Python interpreter executable as the one running the IPython kernel.
2. There is no explicit disconnect calls in the parent and child processes. IOW, `Spawn()` returns an intercommunicator and you should disconnect it (in both sides) before Python garbage-collect the object. If you properly disconnect, then I would expect things to behave OK.

```python
import mpi4py.MPI as MPI
comm_world = MPI.COMM_WORLD
comm_world.Spawn(
    # get the same python executable that is currently running
    sys.executable,
    ["-c",  "import mpi4py.MPI as MPI; print(MPI.COMM_WORLD.Get_rank()); MPI.Comm.Get_parent().Disconnect()"],
    1,
).Disconnect()
```

**Comment by IsaacWarren** [comment]
@dalcinl really appreciate you taking a look. I just tried
```
import mpi4py.MPI as MPI
import atexit
import sys

comm_world = MPI.COMM_WORLD
intercomm = comm_world.Spawn(
    sys.executable,
    ["-c",  "import mpi4py.MPI as MPI; print(MPI.COMM_WORLD.Get_rank()); MPI.Comm.Get_parent().Disconnect()"],
    1,
)

def exit_handler():
    global intercomm 
    intercomm.Disconnect()
atexit.register(exit_handler)
```
and it seems to cleanup properly, thank you. Closing
